{% set name = "jupyterlab-plotly-extension" %}
{% set version = "1.0.0" %}
{% set sha256 = "4d9c049c3ce8fd356ad2008a6d83276463d6aef0abdd8a514e17cbffc350e820" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyterlab/jupyter-renderers/archive/@jupyterlab/plotly-extension@{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python

requirements:
  build:
    - nodejs
  host:
    - jupyterlab
    - python >=3.5
  run:
    - jupyterlab
    - nodejs
    - python >=3.5

test:
  commands:
    - jupyter labextension list
    - jupyter lab build

about:
  home: https://github.com/jupyterlab/jupyter-renderers/blob/master/packages/plotly-extension
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A JupyterLab extension for rendering Plotly charts
  dev_url: https://github.com/jupyterlab/jupyter-renderers

extra:
  recipe-maintainers:
    - dbast
    - blink1073
    - uday1889
