travis:
  secure:
    BINSTAR_TOKEN: puGjXbXMiZj7DWGY6Gccma31tWUf0wV+3CtFCNeFRaVu/6SVUmAOuGpEjIIAwem8uXTpMtqXBcXSg1fPUJO+9t000hWCISKhIgfGXn3wqdg1ALwZ53Z323aw6YlkZsmTOLZ43xtdb/5Q3LctOym5kHMLYZsYHIpjycxS8Nc697gTcXhh5lPRf2mVZaLeffX151ndXhypOY+j7QNrjwovzDfV/0gbs/hP+u0cKVgPdo+JG9bE7PH4Z0evxl8rnGe/7IdNwF0wBw58ebu3cH4BuQepxx/Lzjb7YbX5eTEkN97gzKTxPmWROnb26ZBhChqeZgxArJDNRetFrpJJKMfBu51sY3osr6jj6ByI/OnhPQbm7jKRRgUMjlsFG9yk+EVVroXZKGyPJ2YdSEYaLqlz7v37OGghXCiBC91D6RAay/FjXZVaquu8MDwNOs9eK72Gr7YGNkWh2VjAO4uqwi17h/CO4xJoK+mE5mk3OkodSpzy7zMn4cCkRszfKhg6ZYCMHNmOZeWUKCmE3c3kQ2GjW8gWVWpeIaSxV/3ADuIDTxuwwzaUVIBYE8WoRgfg6HeAkU7YrPqlo1tFkylnfTM1XrENE6JuDKfRycZCXiZNiHu3IFk93t4yy4yc6Q4jxnBKQkGOLs0pIPVtGYnhgqY8B9Kutoe6MemTg2yFpeuEs/A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
